spring:
  messages:
    basename: messages
    encoding: UTF-8 # 인코딩 문제로 포함
datasource:
  url: jdbc:h2:mem:~/exception
  driver-class-name: org.h2.Driver
  username: sa
  password:
jpa:
  hibernate:
    ddl-auto: none
